arepos:
  auth:
    registration-enabled: false
    cookie-secure: true
  swagger:
    enabled: false

server:
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: never
