{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "arepos-server.fullname" . }}
  labels:
    {{- include "arepos-server.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "arepos-server.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingress.warchiPodLabels | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress:
    {{- if .Values.networkPolicy.egress.allowDns }}
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
    {{- if and .Values.postgresql.enabled .Values.networkPolicy.egress.allowPostgresql }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name | quote }}
              app.kubernetes.io/component: postgresql
      ports:
        - protocol: TCP
          port: 5432
    {{- end }}
    {{- if and .Values.minio.enabled .Values.networkPolicy.egress.allowMinio }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name | quote }}
              app.kubernetes.io/component: minio
      ports:
        - protocol: TCP
          port: 9000
    {{- end }}
    {{- if and .Values.cerbos.deploy .Values.networkPolicy.egress.allowCerbos }}
    - to:
        - podSelector:
            matchLabels:
              {{- include "arepos-server.cerbos.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 3592
        - protocol: TCP
          port: 3593
    {{- end }}
{{- end }}
