{{- if and (not .Values.database.existingSecret) .Values.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arepos-server.fullname" . }}-db-secret
  labels:
    {{- include "arepos-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.database.password | quote }}
{{- end }}

