ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255),
    ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'USER',
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE public.users
    ADD CONSTRAINT users_role_check CHECK (role IN ('USER', 'EDITOR', 'ADMIN'));
