# yaml-language-server: $schema=https://api.cerbos.dev/latest/cerbos/policy/v1/Policy.schema.json
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: default
  resource: file
  rules:
    - name: admin-all
      actions: ["*"]
      effect: EFFECT_ALLOW
      roles:
        - admin

    - name: owner-view
      actions: ["view"]
      effect: EFFECT_ALLOW
      roles:
        - reader
        - editor
      condition:
        match:
          expr: request.principal.id == request.resource.attr.ownerId
